### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [yerimpark103/find-lost-animals#6]
Hello

**Report**
I tried to run this project, but I found errors like below. Need more setup?

<img width="944" alt="image" src="https://user-images.githubusercontent.com/4844714/229745865-51d7d0c7-e187-4ba1-91b6-a0f95a8999d5.png">

**Comment by yerimpark103** [comment]
Hello,
Thanks for checking out and reporting the issue. 

Said issue happened due to the `tsconfig` file stuck in `.gitignore` and not being able to get pushed to github. 
This has been solved in a PR, which just got merged to [main](https://github.com/yerimpark103/find-lost-animals/tree/main) branch. 
Please pull `main` and restart the server with `yarn dev`.
Since this is a project which just started and not published on the web yet, you would need an `.env` file in the root folder in order to access the api directly. I'll send you the file via email. 

Thanks.
